- name: Install Apache HTTPD
  hosts: web
  become: true

  tasks:
    - name: wait untill host come up.
      ansible.builtin.wait_for_connection:
        timeout: 120

    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Start HTTPD
      service:
        name: httpd
        state: started
        enabled: true
